all: evilchild.o                                                                                       
	gcc -o evilchild evilchild.o -lpthread                                                                
		                                                                                                    
evilchild.o: evilchild.c                                                                                  
	gcc -c evilchild.c                                                                                 
		                                                                                                    
clean:                                                                                              
	rm -f *.o evilchild 
